config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter

  validates :body,  :presence => true
  validates :commenter, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes, :email, :open
 
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}
  has_many :comments, :dependent => :destroy
  has_many :tags
 
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	 http_basic_authenticate_with :name => "admin", :password => "secret", :only => :destroy
 
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
    UserMailer.comment_created(@post).deliver
  end

  def delete

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with :name => "admin", :password => "secret", :except => [:index, :show, :new]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      # Kommentaaride kustutamiseks
      Comment.delete_all(:id => params[:comment_ids])
      # redirect_to edit_post_path(@post)
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end      
    end

  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Commendt:</b>
  <%= comment.body %>
</p>

app/views/comments/_edit.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<div class="">
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field" class="span12">
    <%= f.label :Comment %><br />
    <%= f.text_area :body, class:"span12"%>
  </div>
  <div class="actions">
    <%= f.submit "ADD A COMMENT", class: "btn" %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "BLOG", posts_path, id: "logo" %>
          <nav>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 <table>
  <tr>
    <td> <h4>Author's e-mail </h4> </td>
    <td>  <%= post_form.text_field :email %></td>
  </tr>
  <tr>
    <td> <h4>Name</h4> </td>
    <td> <%= post_form.text_field :name %></td>
  </tr>
  <tr>
    <td> <h4>Title</h4> </td>
    <td>  <%= post_form.text_field :title %></td>
  </tr>
  <tr>
    <td> <h4>Are comments allowed? </h4> </td>
    <td> <%= check_box "post", "open"%></td>
  </tr>
  </table>
  <div class="field" class="span12">
    <%= post_form.text_area :content, :class => 'span12'%>
  </div>
  <h2>tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
  </div>
    <%= post_form.submit class: "btn btn-large" %>
<% end %>

app/views/posts/_post_edit.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 <table>
  <tr>
    <td> <h4>Author's e-mail </h4> </td>
    <td>  <%= post_form.text_field :email %></td>
  </tr>
  <tr>
    <td> <h4>Name</h4> </td>
    <td> <%= post_form.text_field :name %></td>
  </tr>
  <tr>
    <td> <h4>Title</h4> </td>
    <td>  <%= post_form.text_field :title %></td>
  </tr>
  <tr>
    <td> <h4>Are comments allowed? </h4> </td>
    <td> <%= check_box "post", :open%></td>
  </tr>
  </table>
  <div class="field" class="span12">
    <%= post_form.text_area :content, :class => 'span12'%>
  </div>
  <h2>tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
  </div>

  <% @post.comments.each do |comment| %>
  	<p>
    <div id="info">
      Select for deleting 
      <%= check_box_tag "comment_ids[]", comment.id %>
    </div>
	  <b>Commenter:</b>
	  <%= comment.commenter %> <br>
	  </p>
	 
	<p>
	  <b>Comment:</b>
	  <%= comment.body %>
	</p>
  <% end %>

    <%= post_form.submit "SAVE", class: "btn" %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'post_edit' %>
  <div class="actions">
    <%= link_to 'Delete post', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large"%>
  </div>

app/views/posts/index.html.erb
<%= link_to 'Create a new post', new_post_path, class: "btn btn-large btn-block"%>

<table class="span12">
<% @posts.each do |post| %>
    <tr><td><h1><%= link_to post.name, post %></h1></td>
    <td>by <%= post.name %></td></tr>
<% end %>
</table>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <h3><%= @post.title %></h3>
</p>
 
<p>
  <div class="span12"><%= @post.content%></div>
</p>

<p>
  <b>by </b>
  <div ><%= @post.name%></div>
  <div ><%= @post.created_at%></div>
</p>
 
<p>
  <%= join_tags(@post) %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<% if @post.open? %>
	<%= render "comments/form"%>
<% end %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>